name: Start the app and run tests

on:
  push:
    branches: [ cucumber-automation ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Cucumber tag to run (e.g. @smoke, @integration)'
        required: true
        default: '@Sample'

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build the child project (without tests)
        run: ./gradlew :sample-cucumber-app:build -x test

      - name: Start the Spring Boot app (from child project)
        run: java -jar sample-cucumber-app/build/libs/*.jar &

      - name: Wait for app to start (adjust port and timeout as needed)
        run: |
          echo "Waiting for the app to start..."
          for i in {1..30}; do
            if curl -s http://localhost:8080/actuator/health | grep UP; then
              echo "App is up!"
              break
            fi
            echo "Waiting..."
            sleep 2
          done

      - name: Run Cucumber integration tests from child project
        run: |
          ./gradlew :sample-cucumber-app:test -Dcucumber.filter.tags="${{ github.event.inputs.tag }}"
          echo "CURRENT_DATETIME=$(date -u '+%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

      - name: Upload Cucumber HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report-for-${{ github.event.inputs.tag }}-ran-at-${{ env.CURRENT_DATETIME }}
          path: sample-cucumber-app/build/reports